# Generated by Django 6.0.7 on 2026-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
