# Generated by Django 6.0.7 on 2026-07-31 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='idx_proj_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager', 'status'], name='idx_proj_mgr_status'),
        ),
    ]
