# Generated by Django 6.0.7 on 2026-08-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_project_idx_proj_status_project_idx_proj_mgr_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinvitation",
            name="email_delivery_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectinvitation",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
