# Generated by Django 6.0.7 on 2026-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_risk_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='predicted_risk',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='risk_confidence',
            field=models.FloatField(default=0),
        ),
    ]
