# Generated by Django 6.0.7 on 2026-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_last_risk_update_task_predicted_risk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("progress", "In Progress"),
                    ("review", "Review"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="todo",
                max_length=20,
            ),
        ),
    ]
