# Generated by Django 6.0.7 on 2026-07-31 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_idx_proj_status_project_idx_proj_mgr_status'),
        ('tasks', '0003_alter_task_deadline_alter_task_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='idx_task_proj_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'predicted_risk'], name='idx_task_proj_risk'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'deadline'], name='idx_task_proj_deadline'),
        ),
    ]
